### ISSUE TITLE
Grimlite Rev v1.3 (Skymeister)

### ISSUE THREAD

**Issue by Stewbed** [GentleGanku/GrimliteRev#11]
Grimoire is always shown ON-TOP, Any tool from TOOLS, PACKETS isn't shown on top anymore but behind the client which is inconvenient. thank you for fixing the Accept quest issue regardless <3

**Comment by GentleGanku** [comment]
I have reverted the On-top Priority update on every panels and changed the Grim main panel's behavior to a different one, on the newer update. Hope you're satisfied with it!
