### ISSUE TITLE
Selecting Issues after "Stop Bot Command"

### ISSUE THREAD

**Issue by Stewbed** [GentleGanku/GrimliteRev#12]
This actually was from a while ago, it doesn't affect botting that much since we can re-open the client again.
![Untitled video ‐ Made with Clipchamp](https://user-images.githubusercontent.com/62359842/162259563-61fe37da-0f75-4393-96da-09f86dd0f5ac.gif)

**Comment by GentleGanku** [comment]
You can toggle the Select Mode to Multiline again by right-clicking an empty space and then tick the Multiline Toggle.

![vwKtE3sjXH](https://user-images.githubusercontent.com/87234700/162337278-564f4bf1-280d-4ccf-9662-6774452364a9.gif)

**Comment by Stewbed** [comment]
This indeed the case. Ty <3
