### ISSUE TITLE
Error everytime [Provoke in cell] command is turned on, either by options or cmd.

### ISSUE THREAD

**Issue by YashaYasuo** [GentleGanku/GrimliteRev#16]
**Error would persist even when clicking on continue and would disappear if provoke is turned off manually.**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grimoire.Game.World.MonstersInCell(String cell)
   at Grimoire.Botting.OptionsManager.<Provoke>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by GentleGanku** [comment]
This is fixed on the new update, please check again.

**Comment by YashaYasuo** [comment]
Ok, thank you ♥
