### ISSUE TITLE
Flash Player is not detected

### ISSUE THREAD

**Issue by zrovihr** [GentleGanku/GrimliteRev#23]
I have flash player from archive.org installed. I can open flash games online just fine but the bot asks me to install adobe flash player

**Comment by zrovihr** [comment]
I solved it by installing Adobe Flash Pro. sorry for the trouble.

**Comment by cmdbredillas** [comment]
how did you fix this bro?

**Comment by zrovihr** [comment]
> how did you fix this bro?

as I said in the comment, you install Adobe flash pro. which is now unavailable for public, I would suggest to look it up in Archive.org, Honestly i dont remember and I can't guarantee.
