### ISSUE TITLE
auto pick command/auto drop picker

### ISSUE THREAD

**Issue by Nero185** [GentleGanku/GrimliteRev#3]
The GrimliteRev Bot won't activate its auto pick command which results the player to manually get the drop.

**Comment by InjeraGoh** [comment]
Has the issue of auto-pick-up been resolved yet? Is there any progress-update that could be announced?

**Comment by KhaiTHSE130158** [comment]
Excuse me but auto pick up and all packet options are not working, also the option infinite attack range is sometimes not working.
